#!/bin/bash

read X
read Y

if [[ $X -le 100 ]] && [[ $X -ge -100 ]] && [[ $Y -le 100 ]] && [[  $Y -ge -100 ]]  && [[ $Y -ne 0 ]]
then
	echo $(expr $X '+' $Y)
	echo $(expr $X '-' $Y)
	echo $(expr $X '*' $Y)
	echo $(expr $X '/' $Y)
fi
